project:
  type: website
  output-dir: docs

website:
  title: "Atoms and Light"
  site-url: https://www.atomsandlight.com
  favicon: general_images/favicon.svg
  navbar:
    logo: general_images/site-logo.png
    logo-alt: "Atoms and Light logo"
    left:
      - href: about.qmd
        text: About Me

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    grid:
      body-width: 1000px
      margin-width: 200px



